### ISSUE TITLE
400 Client Error en request_code()

### ISSUE THREAD

**Issue by cccaballero** [adbenitez/todus#6]
Ante todo gracias, y muy buen trabajo!!

Estoy recibiendo un error al intentar utilizar la función `request_code()` de la siguiente manera:

    todus_client = client.ToDusClient()
    todus_client.request_code('+53xxxxxxxx')

Estoy asumiendo que el orden de ejecucuón sería `request_code()`, `validate_code` y `login()`, y el error que recibo es:

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://auth.todus.cu/v2/auth/users.reserve
```

**Comment by adbenitez** [comment]
hola @cccaballero, acabo de añadir una sección "quickstart" al README con un ejemplo de como usar esta biblioteca para iniciar sessión y subir y bajar archivos.


> todus_client.request_code('+53xxxxxxxx')

el problema es que es el número sin el "+" delante, acabo de añadir una función en utils.py llamada `normalize_phone_number` úsala y convertirá un número dado en cualquier formato como `+53 12345678` en el formato apropiado (que vendría siendo `5312345678`)
