### ISSUE TITLE
Usar terminate en vez de kill para Python 3.6

### ISSUE THREAD

**Issue by oleksis** [adbenitez/todus#7]
Usar `p.terminate()` en Python 3.6

https://github.com/adbenitez/todus/blob/aa03d549f39b5170b9ce947a2319836890479971/todus/client.py#L44

**Comment by oleksis** [comment]
Otro Issue es que `multiprocess` en Windows las funciones para las tareas `target` no son accesibles pues son anónimas. Puedes [ver una anternativa](https://github.com/oleksis/todus/blob/5ea0f594bbc43476d6e4f4c0ab69d566344779ea/todus/client.py#L119)

**Comment by adbenitez** [comment]
luego de arreglar la razón real que causaba que el programa se "colgara" para siempre en realidad ya no hace falta eso de correr en un proceso y matarlo, se pudiera quitar el uso de procesos completamente

**Comment by adbenitez** [comment]
ya eliminé eso del proceso completamente, así que ya este problema fue resuelto :)
